name: Deploy to Development Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GamingRewampPVTSSHKey }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        run: ssh-keyscan -H 82.27.0.172 >> ~/.ssh/known_hosts

      - name: Copy files to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 82.27.0.172
          username: root
          key: ${{ secrets.GamingRewampPVTSSHKey }}
          source: "."
          target: "/www/wwwroot/gamingdevapinew.gaminghelperonline.com"

      - name: Set execute permissions for files
        run: |
          ssh -i ~/.ssh/id_ed25519 root@82.27.0.172 "chmod -R 755 /www/wwwroot/gamingdevapinew.gaminghelperonline.com"

      - name: Check if npm and pm2 are installed
        run: |
          ssh -i ~/.ssh/id_ed25519 root@82.27.0.172 "which npm && which pm2"

      - name: Rebuild native modules on the server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@82.27.0.172 "cd /www/wwwroot/gamingdevapinew.gaminghelperonline.com && npm rebuild bcrypt --build-from-source"

      - name: Install dependencies and restart application
        run: |
          ssh -i ~/.ssh/id_ed25519 root@82.27.0.172 "
            cd /www/wwwroot/gamingdevapinew.gaminghelperonline.com && \
            npm install --production && \
            pm2 delete gamingDev || true && \
            pm2 start app.js --name gamingDev && \
            pm2 save
          "